### PR TITLE
rhbz1241346 - fix file mapping rule JAXB mapping and reduce debug noice

### PR DESCRIPTION
**Pull request by huangp**
- [ ] need to pack port to release

https://bugzilla.redhat.com/show_bug.cgi?id=1241346

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1:

**Comment by seanf** [comment]
noice -> noise

**Comment by definite** [comment]
:+1:

**Comment by huangp** [comment]
backported to release at aa7d429

**Pull request merged**
