### PR TITLE
rhbz1124630 - need to add header for all requests

### PR DESCRIPTION
**Pull request by huangp**

### CODE REVIEW

**Comment by huangp** [comment]
@aeng can you review this one please? Thanks

**Comment by aeng** [comment]
:+1:

**Comment by huangp** [comment]
@definite can you test this please? 
- [ ] zanata init works
- [ ] put account works
- [ ] copy trans works

**Comment by huangp** [comment]
last commit fixed an overlooked bug:
when you select a project and a version using zanata init, if the project and version don't have project type specified, it will run into exception. Now this is fixed.
Possible test cases for zanata init:
- [ ] run zanata init to select a project without project type
- [ ] select a version with different project type compared to its project
- [ ] select a project and version both don't have project type

**Comment by definite** [comment]
:+1:

**Pull request merged**
