### PR TITLE
Support Qt ts file format

### PR DESCRIPTION
**Pull request by djansen-redhat**
Depends on https://github.com/zanata/zanata-api/pull/35

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-client/102)

### CODE REVIEW

**Comment by davidmason** [comment]
:+1:   :hamburger:

**Comment by definite** [comment]
It does not seem to handle context. Not sure whether this should be the blocker.
Dataset: qt-everywhere (qt-4.8.7)

Steps to reproduce
1. Push translations/qt.ts
2. In WebUI, file translations/qt.ts
3. Search "Invalid URL"

Expected:
   First "Invalid URL" should have message context `FakeReply"`
   Second "Invalid URL" should have message context `Phonon::MMF`

Actual:
   All "Invalid URL" did not have message context at all.

**Comment by definite** [comment]
:+1: 
Note that this PR does not support context. The context support will be address in other bug.

**Comment by definite** [comment]
QT ts context support issue:
https://zanata.atlassian.net/browse/ZNTA-1132

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Pull request merged**
