### PR TITLE
Add Read the docs documentation.

### PR DESCRIPTION
**Pull request by carlosmunoz**
Currently uses the default readthedocs theme, but can be customized with our own theme. This is an almost exact copy of the content on zanata.org/help that relates to the client.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@seanf @lukebrooker Do you guys mind taking a look at this?
A draft build of this Pull Request can be seen at http://zanata-client.readthedocs.org/en/readthedocs/

**Comment by seanf** [comment]
@carlosmunoz Shouldn't that be something like http://zanata-client.readthedocs.org/en/latest/readthedocs/ so that we can different versions?  (I know, it's just a draft.)

**Comment by seanf** [comment]
@carlosmunoz oh, `readthedocs` is a version.  (?!)  You got me!

**Comment by carlosmunoz** [comment]
Yes :smile: , just a placeholder for the time being, once it's on master I was thinking:
master => latest
release => stable
A few (?) previous releases for reference.

**Comment by seanf** [comment]
@carlosmunoz Is there a limit on the number of releases?

**Comment by seanf** [comment]
@carlosmunoz 
Can we make "Edit on GitHub" link to the actual file?
The issue tracker link is not clickable.  Is the main page new content, or was it taked from zanata.org/help somewhere?

**Comment by carlosmunoz** [comment]
Answers:
1. We could point it to the actual file, but we have to build our own custom template.
2. Main page content is a placeholder, we should edit.
3. There doesn't seem to be a limit, you can specify how many major, minor and point versions you want to keep.

**Comment by seanf** [comment]
We might want to find a way of disabling syntax highlighting for some of the sample console output in the docs.

**Comment by carlosmunoz** [comment]
Which one for example?

**Comment by carlosmunoz** [comment]
Never mind, found it.

**Comment by seanf** [comment]
@carlosmunoz Regarding "Edit on GitHub", perhaps we could just link to https://github.com/zanata/zanata-client/tree/master/docs (the subdirectory)

**Comment by carlosmunoz** [comment]
@seanf Sure thing.

**Comment by seanf** [comment]
@carlosmunoz It looks like a great start.  I like the side menu.  But the search feature doesn't seem to work very well - searching for `zanata.xml` doesn't give many results.

**Pull request merged**
