### PR TITLE
Default 'validate' option to CONTENT as in help text

### PR DESCRIPTION
**Pull request by seanf**
This should also prevent a potential null pointer exception.

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-client/123)

### CODE REVIEW

**Comment by seanf** [comment]
@aeng Mind reviewing this one?

**Comment by aeng** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-client-commands/src/main/java/org/zanata/client/commands/push/PushOptionsImpl.java, line 260 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-client/123#-KNEGP7ULtJjfpxGoh_F:-KNEGP7VQTFcICgYi0sl:561457947) ([raw file](https://github.com/zanata/zanata-client/blob/6fcbfaeba8f2f7b0c9ca235f4e26dfa2640428a5/zanata-client-commands/src/main/java/org/zanata/client/commands/push/PushOptionsImpl.java#L260)):*
> ```Java
>     @Nonnull
>     public String getValidate() {
>         if (validate == null) {
> ```

Do we need to check for empty string too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/123)*

**Comment by seanf** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-client-commands/src/main/java/org/zanata/client/commands/push/PushOptionsImpl.java, line 260 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-client/123#-KNEGP7ULtJjfpxGoh_F:-KNF7Uh5RsjnBPRjOeg-:-2136536822) ([raw file](https://github.com/zanata/zanata-client/blob/6fcbfaeba8f2f7b0c9ca235f4e26dfa2640428a5/zanata-client-commands/src/main/java/org/zanata/client/commands/push/PushOptionsImpl.java#L260)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Do we need to check for empty string too?
</details>
No, this is about making the code null-safe. If someone explicitly sets the validate option to the empty string, they will get an error about the invalid value later on. I wouldn't want to treat empty string the same as null (which basically means "use the default").

Honestly, we should probably rewrite all these methods just to use the ValidationType enum, not String, but I don't want to get into that at the moment, I just want to eliminate the NPE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/123)*

**Comment by seanf** [comment]
@aeng Could you please review the changes?

**Comment by seanf** [comment]
@aeng I haven't heard back from you on this one.

**Comment by aeng** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/123#-:-KPAPZdtWvguTD_-eUYZ:bnfp4nl)*

**Comment by aeng** [comment]
-(Awaiting review) 
+Reviewed +(On QA) 

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/123#-:-KPAPfEWigf1UNXy3Fvk:baawxty)*

**Comment by seanf** [comment]
@djansen-redhat Is this one on the radar?

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
Sorry @seanf this was not on my radar, I'll get on it right away

**Comment by djansen-redhat** [comment]
:shipit: Looks fine to me

**Comment by djansen-redhat** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/123)*

**Pull request merged**
