### PR TITLE
rhbz1222730 - add options to use cache in java client

### PR DESCRIPTION
**Pull request by huangp**

### CODE REVIEW

**Comment by seanf** [comment]
I recommend that @carlosmunoz review this one.  I assume these options are similar to the Maven options?

**Comment by huangp** [comment]
Yes. except maven has different naming convention and the way to set it.

**Comment by seanf** [comment]
Sure, that's to be expected.

**Comment by carlosmunoz** [comment]
So, is this all that was missing? Looks like the variables were already there, and the code to use them as well, we just need to be able to set the vars. If that's the case, then :+1:

**Comment by definite** [comment]
:+1:

**Pull request merged**
