### PR TITLE
Basic JSON support

### PR DESCRIPTION
**Pull request by djansen-redhat**
Depends on https://github.com/zanata/zanata-api/pull/58
Related to https://github.com/zanata/zanata-server/pull/1261

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-client/125)

### CODE REVIEW

**Comment by seanf** [comment]
@djansen-redhat This has a conflict. But I'm not sure if it's still needed, after https://github.com/zanata/zanata-client/pull/113

**Comment by djansen-redhat** [comment]
@seanf rebased, and replaced filetypes with 113's update

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/125#-:-KTHCxp8WCEgEgeY95wv:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Pull request merged**
