### PR TITLE
Update glossary reader

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-108

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@aeng Hey Alex, any chance you can provide more details on what the changes are for this pull request?

**Comment by definite** [comment]
@aeng is it safe to back port to release branch?

**Comment by aeng** [comment]
@definite nope. Its for master branch.

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@aeng This branch has conflicts with `integration/master`.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-client/commit/325cda4c7c772686bf8bca733296f20abefa2840

**Pull request closed without merging**
