### PR TITLE
ZNTA-1178 - fix issue pulling file type project

### PR DESCRIPTION
**Pull request by huangp**
https://zanata.atlassian.net/browse/ZNTA-1178

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-client/118)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/118)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/118#-:-KKMZVQXwaPl9Oj26PKR:1417088721)*

**Comment by definite** [comment]
This failed when pulling odt from locale sr@latin
pulling properties from sr@latin does not fail
Data set: freemind

JBWEB000065: HTTP Status 500 - org.zanata.exception.FileFormatAdapt
erException: Unable to generate translated file

[ERROR] Operation failed: operation returned 500 (Internal Server Error): <html><head><title>JBWEB000065: HTTP Status 500 - org.zanata.exception.FileFormatAdapter
Exception: Unable to generate translated file</title><style></style> </head><body><h1>JBWEB000065: HTTP Status 500 - org.zanata.exception.FileFormatAdapterException: Unable to generate translated file</h1><HR size="1"
noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000066: Exception report</p><p><b>JBWEB000068: message</b> <u>org.zanata.exception.FileFormatAdapterException:
Unable to generate translated file</u></p><p><b>JBWEB000069: description</b> <u>JBWEB000145: The server encountered an internal error that prevented it from fulfi
lling this request.</u></p><p><b>JBWEB000070: exception</b> <pre>org.jboss.resteasy.spi.UnhandledException: org.zanata.exception.FileFormatAdapterException: Unable to generate translated file
	org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:247)
	org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:165)
	org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:452)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:396)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:199)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	org.apache.deltaspike.servlet.impl.event.EventBridgeFilter.doFilter(EventBridgeFilter.java:59)
	org.apache.deltaspike.servlet.impl.produce.RequestResponseHolderFilter.doFilter(RequestResponseHolderFilter.java:63)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	org.zanata.servlet.DuplicateParamFilter.doFilter(DuplicateParamFilter.java:69)
	org.zanata.servlet.JavaMelodyFilter.doFilter(JavaMelodyFilter.java:65)
	org.zanata.servlet.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:76)
	org.zanata.servlet.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:88)
	org.zanata.rest.RestLimitingFilter.lambda$doFilter$0(RestLimitingFilter.java:130)
	org.zanata.limits.RestCallLimiter.acquireActivePermit(RestCallLimiter.java:94)
	org.zanata.limits.RestCallLimiter.tryAcquireAndRun(RestCallLimiter.java:68)
	org.zanata.limits.RateLimitingProcessor.process(RateLimitingProcessor.java:56)
	org.zanata.limits.RateLimitingProcessor.processForApiKey(RateLimitingProcessor.java:37)
	org.zanata.rest.RestLimitingFilter.doFilter(RestLimitingFilter.java:145)
</pre></p><p><b>JBWEB000071: root cause</b> <pre>org.zanata.exception.FileFormatAdapterException: Unable to generate translated file
	org.zanata.adapter.OkapiFilterAdapter.writeTranslatedFile(OkapiFilterAdapter.java:365)
	org.zanata.rest.service.FileService$FormatAdapterStreamingOutput.write(FileService.java:483)
	org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:32)
	org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:17)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:131)
	org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:60)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:120)
	org.jboss.resteasy.core.interception.WriterInterceptorRegistry$MessageBodyWriterContextFacade.proceed(WriterInterceptorRegistry.java:147)
	org.zanata.rest.JsonPWriterInterceptor.write(JsonPWriterInterceptor.java:31)
	org.zanata.rest.JsonPWriterInterceptor$Proxy$_$$_WeldClientProxy.write(JsonPWriterInterceptor$Proxy$_$$_WeldClientProxy.java)
	org.jboss.resteasy.core.interception.WriterInterceptorRegistry$WriterInterceptorFacade.aroundWriteTo(WriterInterceptorRegistry.java:169)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
	org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo(GZIPEncodingInterceptor.java:100)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
	org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:98)
	org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:447)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:396)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:199)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	org.apache.deltaspike.servlet.impl.event.EventBridgeFilter.doFilter(EventBridgeFilter.java:59)
	org.apache.deltaspike.servlet.impl.produce.RequestResponseHolderFilter.doFilter(RequestResponseHolderFilter.java:63)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	org.zanata.servlet.DuplicateParamFilter.doFilter(DuplicateParamFilter.java:69)
	org.zanata.servlet.JavaMelodyFilter.doFilter(JavaMelodyFilter.java:65)
	org.zanata.servlet.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:76)
	org.zanata.servlet.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:88)
	org.zanata.rest.RestLimitingFilter.lambda$doFilter$0(RestLimitingFilter.java:130)
	org.zanata.limits.RestCallLimiter.acquireActivePermit(RestCallLimiter.java:94)
	org.zanata.limits.RestCallLimiter.tryAcquireAndRun(RestCallLimiter.java:68)
	org.zanata.limits.RateLimitingProcessor.process(RateLimitingProcessor.java:56)
	org.zanata.limits.RateLimitingProcessor.processForApiKey(RateLimitingProcessor.java:37)
	org.zanata.rest.RestLimitingFilter.doFilter(RestLimitingFilter.java:145)
</pre></p><p><b>JBWEB000071: root cause</b> <pre>java.lang.IllegalArgumentException: The locale identifier 'sr@latin' contains at least one invalid character.
	net.sf.okapi.common.LocaleId.normalize(LocaleId.java:405)
	net.sf.okapi.common.LocaleId.&lt;init&gt;(LocaleId.java:217)
	net.sf.okapi.common.LocaleId.fromString(LocaleId.java:419)
	org.zanata.adapter.OkapiFilterAdapter.writeTranslatedFile(OkapiFilterAdapter.java:351)
	org.zanata.rest.service.FileService$FormatAdapterStreamingOutput.write(FileService.java:483)
	org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:32)
	org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:17)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:131)
	org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:60)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:120)
	org.jboss.resteasy.core.interception.WriterInterceptorRegistry$MessageBodyWriterContextFacade.proceed(WriterInterceptorRegistry.java:147)
	org.zanata.rest.JsonPWriterInterceptor.write(JsonPWriterInterceptor.java:31)
	org.zanata.rest.JsonPWriterInterceptor$Proxy$_$$_WeldClientProxy.write(JsonPWriterInterceptor$Proxy$_$$_WeldClientProxy.java)
	org.jboss.resteasy.core.interception.WriterInterceptorRegistry$WriterInterceptorFacade.aroundWriteTo(WriterInterceptorRegistry.java:169)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
	org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo(GZIPEncodingInterceptor.java:100)
	org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
	org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:98)
	org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:447)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:396)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:199)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	org.apache.deltaspike.servlet.impl.event.EventBridgeFilter.doFilter(EventBridgeFilter.java:59)
	org.apache.deltaspike.servlet.impl.produce.RequestResponseHolderFilter.doFilter(RequestResponseHolderFilter.java:63)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	org.zanata.servlet.DuplicateParamFilter.doFilter(DuplicateParamFilter.java:69)
	org.zanata.servlet.JavaMelodyFilter.doFilter(JavaMelodyFilter.java:65)
	org.zanata.servlet.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:76)
	org.zanata.servlet.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:88)
	org.zanata.rest.RestLimitingFilter.lambda$doFilter$0(RestLimitingFilter.java:130)
	org.zanata.limits.RestCallLimiter.acquireActivePermit(RestCallLimiter.java:94)
	org.zanata.limits.RestCallLimiter.tryAcquireAndRun(RestCallLimiter.java:68)
	org.zanata.limits.RateLimitingProcessor.process(RateLimitingProcessor.java:56)
	org.zanata.limits.RateLimitingProcessor.processForApiKey(RateLimitingProcessor.java:37)
	org.zanata.rest.RestLimitingFilter.doFilter(RestLimitingFilter.java:145)
</pre></p><HR size="1" noshade="noshade"></body></html>

**Comment by huangp** [comment]
@definite please report that as a separate issue. This PR is to fix general file type project pull. The issue is to do with locale with variant.

**Comment by definite** [comment]
The sr@latin is tracked by https://zanata.atlassian.net/browse/ZNTA-1179

**Comment by definite** [comment]
:+1:

**Pull request merged**
