### PR TITLE
Allow anonymous pull command

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1172618

See https://github.com/zanata/zanata-server/pull/737 for server side changes.

### CODE REVIEW

**Comment by seanf** [comment]
@aeng it's odd that you didn't have to touch any stats-related commands.  What's happening with it/them?

**Comment by aeng** [comment]
stats related is all pullCommand which has doesn't require auth. Anyway, @davidmason is making changes by putting the `requireAuth` options into `opts` which I think its a cleaner solution.

**Comment by seanf** [comment]
`GetStatisticsCommand` should not require auth (at least from the client side; let the server decide).

**Comment by seanf** [comment]
Also `ListRemoteCommand`, ideally.

**Comment by davidmason** [comment]
Commands that should return `false` for `isAuthRequired()` (**please edit this directly to add any**, use ~~strikethrough~~ to remove any if you disagree)

- [ ] `GetStatisticsCommand`
- [ ] `ListRemoteCommand`
- [ ] `PublicanPullCommand`
- [ ] `PullCommand`
- [ ] `RawPullCommand`

**Comment by seanf** [comment]
@davidmason that list looks right to me.

**Comment by davidmason** [comment]
@seanf @aeng 

I updated the code, but the build is failing to run checkstyle, giving this error: `Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'allowEmptyLoops' in module WhitespaceAround does not exist`. I get the same error locally on the branch and directly on release when I run `mvn checkstyle:check`.

Any ideas?

**Comment by seanf** [comment]
@davidmason your changes look good. :+1:

**Comment by seanf** [comment]
It sounds like the checkstyle config (in master) might be newer than the
checkstyle plugin (in release).

On 2015-03-24 12:35, David Mason wrote:
> @seanf <https://github.com/seanf> @aeng <https://github.com/aeng>
> 
> I updated the code, but the build is failing to run checkstyle, giving
> this error: |Failed during checkstyle configuration: cannot initialize
> module TreeWalker - Property 'allowEmptyLoops' in module
> WhitespaceAround does not exist|. I get the same error locally on the
> branch and directly on release when I run |mvn checkstyle:check|.
> 
> Any ideas?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-client/pull/54#issuecomment-85307980>.
> 


-- 
Sean Flanigan

Principal Software Engineer
Localisation Tools Engineering
Red Hat

**Comment by seanf** [comment]
@davidmason This exposes a bit of a problem in the way the checkstyle config is set up for branches.

Some options I can think of:
1. Disable checkstyle for the moment.
2. Set new values in `zanata-server` `release` for the variables `checkstyle.config.location` and `checkstyle.suppressions.location`, so that they point to the correct tag of `zanata-parent`, not `master`.

**Comment by seanf** [comment]
Another (perhaps simpler) option might be to update the version of checkstyle-maven-plugin.

**Comment by davidmason** [comment]
@seanf that seems to be the case. If I update parent version on release, checkstyle runs. There are a load of checkstyle failures - they should be easy to fix, but that would be rework since they must have been fixed in master. Perhaps they could be cherry-picked.

Does this change even need to go on release branch?

**Comment by aeng** [comment]
:+1:

**Comment by aeng** [comment]
@seanf upgrade zanata-parent dependency to 21 to upgrade the plugin version or override the version in the pom?

**Comment by seanf** [comment]
On 2015-03-24 12:58, David Mason wrote:
> @seanf <https://github.com/seanf> that seems to be the case. If I update
> parent version on release, checkstyle runs. There are a load of
> checkstyle failures - they should be easy to fix, but that would be
> rework since they must have been fixed in master. Perhaps they could be
> cherry-picked.

Probably not worth it, if we can find an easier workaround.

> Does this change even need to go on release branch?

I think it should.  Otherwise we have six months' worth of changes to
deal with.  Who knows how long that might take to package for Fedora?


-- 
Sean Flanigan

Principal Software Engineer
Localisation Tools Engineering
Red Hat

**Comment by seanf** [comment]
On 2015-03-24 13:12, Alex Eng wrote:
> @seanf <https://github.com/seanf> upgrade zanata-parent dependency to 21
> to upgrade the plugin version or override the version in the pom?

The latter.  Upgrading parent could bring in too many other upgrades.


-- 
Sean Flanigan

Principal Software Engineer
Localisation Tools Engineering
Red Hat

**Comment by seanf** [comment]
> 2. Set new values in `zanata-server` `release` for the variables `checkstyle.config.location` and `checkstyle.suppressions.location`, so that they point to the correct tag of `zanata-parent`, not `master`.

Given the facts @davidmason uncovered in trying to upgrade checkstyle, I think option 2 might be our best option.

**Comment by davidmason** [comment]
> 2. Set new values in `zanata-server` `release` for the variables `checkstyle.config.location` and `checkstyle.suppressions.location`, so that they point to the correct tag of `zanata-parent`, not `master`.

Should that be `zanata-client` `release`?

**Comment by seanf** [comment]
Sorry, yes.

**Comment by seanf** [comment]
:+1:

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged in release. https://github.com/zanata/zanata-client/commit/f9b8fc94b07f8d8f9cf40982189a68a8bd0cdac2

**Pull request closed without merging**
