### PR TITLE
feat(glossary export): glossary pull

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-153

https://github.com/zanata/zanata-api/pull/54
https://github.com/zanata/zanata-server/pull/1190
https://github.com/zanata/zanata-common/pull/27

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-client/117)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/pull/GlossaryPullCommand.java, line 69 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-client/117#-KJYURDzIkK8OAtcGTYC:-KJYURDzIkK8OAtcGTYD:1754113354) ([raw file](https://github.com/zanata/zanata-client/blob/565fd319688df0743edcc5d00c41df8f59d9df12/zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/pull/GlossaryPullCommand.java#L69)):*
> ```Java
>             && !fileType.equalsIgnoreCase("csv")) {
>             throw new RuntimeException(
>                 "Option 'zanata.fileType' is not valid. Please use 'csv' or 'pot'");
> ```

you are comparing fileType to "po" but the error message says "pot". I am not sure which one is correctx

---

*[zanata-rest-client/src/main/java/org/zanata/rest/client/InvalidContentTypeFilter.java, line 55 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-client/117#-KJYVH4wwbeeQTOHd5Q-:-KJYVH4wwbeeQTOHd5Q0:1727430026) ([raw file](https://github.com/zanata/zanata-client/blob/565fd319688df0743edcc5d00c41df8f59d9df12/zanata-rest-client/src/main/java/org/zanata/rest/client/InvalidContentTypeFilter.java#L55)):*
> ```Java
>     // we assume only xml, json and streaming output are the valid types (wildcard type is also considered compatible)
>     private static final Pattern VALID_TYPES_REGEX =
>             Pattern.compile("application/.*\\+?(\\*|xml|json|octet-stream)(;.*)?");
> ```

I think from what we discussed we are going to allow application/.* 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/117)*

**Comment by aeng** [comment]
Review status: 14 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/pull/GlossaryPullCommand.java, line 69 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-client/117#-KJYURDzIkK8OAtcGTYC:-KJYe9M_jzLOdYySFhgz:826181819) ([raw file](https://github.com/zanata/zanata-client/blob/565fd319688df0743edcc5d00c41df8f59d9df12/zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/pull/GlossaryPullCommand.java#L69)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> you are comparing fileType to "po" but the error message says "pot". I am not sure which one is correctx
</details>
should be 'po', we support csv and po format. Corrected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/117)*

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### feat\(glossary export\): glossary pull
> 
> https://zanata.atlassian.net/browse/ZNTA-153
> 
> 
> 
> https://github.com/zanata/zanata-api/pull/54
> 
> https://github.com/zanata/zanata-server/pull/1190
> 
> https://github.com/zanata/zanata-common/pull/27
> 
> 
> 
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-client/117#-:-KJn9L9gCGElAURw7Y8p:1417088721)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Pull request merged**
